name: Entity Inputs

on:
  workflow_dispatch:
    inputs:
      _entity_repository_metadata_name:
        description: Respository Name
        type: string
        required: true
      _entity_environment_spec_ResourceGroup:
        description: Environment Resource Group
        type: string
        required: false
      _entity_environment_spec_Subscription:
        description: Environment Subscription
        type: string
        required: false

env:
  description: This workflow is used to test entity inputs that resolve to entity references.

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - run: echo "### Repository Name ${{ inputs._entity_repository_metadata_name }}! :rocket:" >> $GITHUB_STEP_SUMMARY
      - run: echo "### Environment Resource Group ${{ inputs._entity_environment_spec_ResourceGroup }}! :rocket:" >> $GITHUB_STEP_SUMMARY
      - run: echo "### Environment Subscription ${{ inputs._entity_environment_spec_Subscription }}! :rocket:" >> $GITHUB_STEP_SUMMARY
